### ISSUE TITLE
Multiple paths within XSendFilePaths

### ISSUE THREAD

**Issue by chrisbloom7** [nmaier/mod_xsendfile#1]
I'm using the Windows version of X_SendFile v0.11. I have a directory setup like this:

```
download_packages
|- temporary
|- permanent
```

Inside my vhost config file, I've got the following:

```
LoadModule xsendfile_module modules/mod_xsendfile.so

Listen 8001

<VirtualHost *:8001>
  DocumentRoot "C:/inetpub/apacheroot/test.xxx.com/www"
  ServerName test.xxx.com
  ErrorLog "logs/test.xxx.com-error.log"
  CustomLog "logs/test.xxx.com-access.log" common

    <Directory "/">
        XSendFile on
        XSendFilePath "C:\inetpub\apacheroot\test.xxx.com\download_packages\"
    </Directory> 
</VirtualHost>
```

Now when I set an X_SendFile header such as `header("X_SendFile: permanent/Installer.exe")` I get an error in the Apache error log saying SendFile couldn't find that file (I know it exists)

Previously I had the Path directive set to  `XSendFilePath "C:\inetpub\apacheroot\test.xxx.com\download_packages\temporary"` and could serve files from there by passing in ONLY the name of the file. But now I need to serve the files from either folder. I tried setting multiple XSendFilePath directives as well as passing in both paths at once to a single XSendFilePath directive, but neither worked. (In fact the <del>former</del> <ins>latter</ins> would generate errors in Apache and prevent the server from starting at all.)

What is the proper way to go about setting multiple paths to search in?

**Comment by chrisbloom7** [comment]
Well, I see part of the problem: _You cannot end the directive with a trailing slash!!!_ (IMO, that's worth mentioning in the documentation as it differs from standard Apache [syntax](http://httpd.apache.org/docs/2.2/mod/directive-dict.html#Syntax).

Also, it's probably worth mentioning that both forward- and back-slashes will work in the rest of the path. Ex:

```
XSendFilePath "C:\inetpub\apacheroot\test.xxx.com\download_packages"
```

or

```
XSendFilePath "C:/inetpub/apacheroot/test.xxx.com/download_packages"
```

And finally, I did some further testing and found that if you list multiple `XSendFilePath` directives within the same context, only the first one used. For instance, given the same directory structure in my original post, assume that I have a file in the `temporary` folder named File_a.txt and another file named File_b.txt in the `permanent` folder. Now if I have two FilePath directives, ala

```
<Directory "/">
    XSendFile on
    XSendFilePath "C:\inetpub\apacheroot\test.xxx.com\download_packages\temporary"
    XSendFilePath "C:\inetpub\apacheroot\test.xxx.com\download_packages\permanent"
</Directory> 
```

then I can get the server to send the first file using `header("X_SendFile: File_a.txt")`, but it says it can't find File_b.txt using `header("X_SendFile: File_b.txt")`

However, if I use just a single XSendFilePath directive to point to the parent folder, ala

```
<Directory "/">
    XSendFile on
    XSendFilePath "C:\inetpub\apacheroot\test.xxx.com\download_packages"
</Directory> 
```

I can then send both files as long as I also tell SendFile which subfolder to scan, i.e. `header("X_SendFile: permanent/File_b.txt")`

I'm not sure that that is the ideal solution as you may want to specify multiple directories that don't share the same parent folder, but it just happens to work in my case.

**Comment by nmaier** [comment]
You got a point there, the documentation was wrong there. Updated it.

Use absolute paths whenever you serve something outside the script working directory to avoid troubles.

**Comment by zhangqichuan** [comment]
Oh ,sir , Help me please!
now , I used above configuration, when i download file time ,the file filesize is zero bytes .
so  Help me !
My E-mail is qichuan.zhang@qq.com
