### ISSUE TITLE
Force no ETag output

### ISSUE THREAD

**Issue by guettli** [nmaier/mod_xsendfile#11]
I try to set no etag header, since I set a far future expire header (10 years). I looked at the source,
and I gues there is no way to set no etag header, except I set an empty etag header.

here is the current c code:

``` c
if (
    conf->ignoreETag == XSENDFILE_ENABLED
    || (
      !apr_table_get(r->headers_out, "etag")
      && !apr_table_get(r->err_headers_out, "etag")
    )
  ) {
    apr_table_unset(r->err_headers_out, "etag");
    ap_set_etag(r);
  }
```

Some URLs need ETags, and some don't. That's why I can't modify the apache config. A global option "SendfileDontSetEtag" would be good.

**Comment by nmaier** [comment]
That's what the FileETag directive is for, isn't it?

**Comment by guettli** [comment]
Thank you for this hint. I use a configuration like this now. I use django and mod_wsgi:

```
   WSGIDaemonProcess modwork_vums_dt ...
   WSGIScriptAlias /modwork_vums_dt /home/modwork_vums_dt/modwork_vums/apache/django_wsgi.py
   <Location "/modwork_vums_dt/">
       WSGIProcessGroup modwork_vums_dt
       FileETag none
   </Location>
   XSendFilePath /home/modwork_vums_dt
```
