### ISSUE TITLE
Optionally allow subdirectories of XSendFilePath

### ISSUE THREAD

**Issue by mikehaertl** [nmaier/mod_xsendfile#17]
In earlier versions of mod_xsendfile it was possible to serve files from subdirectories of a permitted directory. Unfortunately this option is gone now again.

I build a simple file storage system where the files are stored in a partitioned directory structure like this (to not have too many files inside one directory):

```
/path/to/files/0/1.jpg
/path/to/files/0/2.jpg
...
/path/to/files/1/100.jpg
/path/to/files/1/101.jpg
...
```

With the current version it's not sufficient to set `XSendFilePath` to `/path/to/files`. I have to configure every single subdirectory. This is very cumbersome. Couldn't we have an option to include all subdirectories?

**Comment by nmaier** [comment]
Works for me, at least on master... Can you please elaborate?

httpd conf

```
XSendFile on
XSendFilePath /tmp
```

test.asis (via mod_asis)

```
X-Sendfile: /tmp/test/2/test
Content-Type: text/plain

FAIL
```

Content of /tmp/test/2/test does not really matter ;)

**Comment by mikehaertl** [comment]
How should i elaborate more? I described my problem above. If i configure `/path` as `XSendFilePath` i am not allowed to send `/path/subdir/file.txt`. I have to add another `XSendFilePath /path/subdir`.

**Comment by mikehaertl** [comment]
Oh, and i don't use master. I use 0.12-1

**Comment by nmaier** [comment]
Stuff like your setup (OS, Apache, libapr, etc.), version of mod_xsendfile you're using - from what source, self-compiled vs. distro provided, more configuration, debug output (see -D_DEBUG when building and log levels), info whether /path or any subdirs are mount points (to some remote fs).

**Comment by nmaier** [comment]
Oh, and of course what generates the X-Sendfile handlers (php, python, ruby, and how it is "connected", like in process mod_php vs. php-fpm)

**Comment by mikehaertl** [comment]
Yes, sorry, i use Ubuntu 11.10 and installed packages: Apache 2.2.20-1ubuntu1.1 and libapache2-mod-xsendfile 0.12-1.

No mount points, all on the same partition.

**Comment by mikehaertl** [comment]
I use the PHP Apache module: libapache2-mod-php5 5.3.6-13ubuntu3.3. If you need more debug output i need some time. Have to set up the not working config first again on a host.

**Comment by nmaier** [comment]
Do your x-sendfile header specify absolute or relative paths?

**Comment by nmaier** [comment]
I just tried that with the /tmp + mod_asis setup from above on Ubuntu 11.10 and distro packages and it works for me

```
# apt-cache policy apache2 libapache2-mod-xsendfile 
apache2:
  Installed: 2.2.20-1ubuntu1.2
  Candidate: 2.2.20-1ubuntu1.2
  Version table:
 *** 2.2.20-1ubuntu1.2 0
        500 http://de.archive.ubuntu.com/ubuntu/ oneiric-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ oneiric-security/main amd64 Packages
        100 /var/lib/dpkg/status
     2.2.20-1ubuntu1 0
        500 http://de.archive.ubuntu.com/ubuntu/ oneiric/main amd64 Packages
libapache2-mod-xsendfile:
  Installed: 0.12-1
  Candidate: 0.12-1
  Version table:
 *** 0.12-1 0
        500 http://de.archive.ubuntu.com/ubuntu/ oneiric/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by mikehaertl** [comment]
Ok, you are right, it works. I double checked my configuration and i really used a symlinked path first:

```
/var/www -> /www
```

In my first attempt i used `XSendFilePath /www/www.some-domain.de/htdocs/files` (doesn't work) and for the subfolders i suddenly used the real path `XSendFilePath /var/www/www.some-domain.de/htdocs/files/0` (worked).

So now it works if i use the real path:

`XSendFilePath /var/www/www.some-domain.de/htdocs/files` 

Sorry for any trouble this may have caused you and thanks for your help!

**Comment by nmaier** [comment]
You're welcome!

**Comment by zhangqichuan** [comment]
Sir , Help me please
now , I've Apache's httpd.conf content is follow:
  <Files *>
    XsendFile on
    XsendFilePath /tmp
          </Files>

and django python view is:
def test_download(request):
        response = HttpResponse()
        response['Content-Type'] =''
        response['Content-Disposition'] = 'attachment; filename=passwdaaaa'
        response['X-Sendfile'] ='/tmp/passwd'
        return response

I mean  when is  IE access http://ip/test_download  time  ,Django Server return static file ,but can do permission authenticated ,
bug, I used the above configuration ,download file is zero bytes .
So Help!  please contact E-mail  qichuan.zhang@qq.com

**Comment by David263** [comment]
In Apache config, I set `XSendFilePath "C:\Web\nsr"` but get 404 error for `local.nsrusa.org/nsr-mtg-archive/`. But `C:\Web\nsr\nsr-mtg-archive\index.php` exists.
