### ISSUE TITLE
Content Encoding

### ISSUE THREAD

**Issue by cfis** [nmaier/mod_xsendfile#22]
We gzip database files on our sever that are then downloaded to ios and Android devices.  We would like to use xsendfile to serve these files (via a Rails app), but it doesn't work because xsendfile drops the Content-Encoding header (as the documents state).  That means the phones networking stacks don't gunzip the files and thus the phone's database code thinks the files are corrupt.

It would be much nicer if xsendfile didn't drop the Content-Encoding file.  As a programmer, in that case I can at least control what headers my app stack is sending back.  As things are now, I can't do anything but modify the xsendfile source code.

If that idea doesn't work, then how about a new configuration parameter that at least let's us turn this feature off?

Thanks - Charlie

**Comment by webgal** [comment]
Oooo! YES! A configuration option for this would be amazing! Especially since sending pre-compressed files would result in even greater efficiency!

**Comment by webgal** [comment]
Just to be clear, for this feature request, below is proposed configuration example (readers, note, this does not yet exist):

**XSendFileAllowContentEncodingHeader**

`Description: Allows Content-Encoding header to pass-through`
`Syntax: 	XSendFileAllowContentEncodingHeader on|off`
`Default: 	XSendFileAllowContentEncodingHeader off`
`Context: 	server config, virtual host, directory, .htaccess`

And here's how such a configuration would behave:

* **off** behavior (default): Content-Encoding is always stripped (like the current version 0.12)
* **on** behavior: Content-Encoding header, if it exists, is allowed to pass through (dream feature)

So now we just need to convince @nmaier this is a good idea :) It is particularly useful when sending out large javascript files which are pre-compressed. I do *not* expect X-SENDFILE to do any compressing whatsoever.

**Comment by Kijewski** [comment]
I just commented out lines [398-399](https://github.com/nmaier/mod_xsendfile/blob/master/mod_xsendfile.c#L398).

> The Content-Encoding header - if present - will be dropped, as the module cannot know if it was set by intention of the programmer or the handler.

The module might not know, but I know that I added the header intentionally. :)

**Comment by cfis** [comment]
Cool thanks.
