### ISSUE TITLE
Add an delete-after-send option

### ISSUE THREAD

**Issue by CybotTM** [nmaier/mod_xsendfile#25]
An option to delete files after they are sent would be very very helpful for temporary files created by the script on the fly:

<?php
...
if ($user->isLoggedIn())
{
    file_put_contents($SomeUserData, $path_to_somefile);
    header("X-Sendfile: $path_to_somefile");
    header("X-Sendfile-DeleteAfter: 1");
    header("Content-Type: application/octet-stream");
    header("Content-Disposition: attachment; filename=\"$somefile\"");
    exit;
}
?>

**Comment by nmaier** [comment]
There is already such a thing in master, as implemented in https://github.com/nmaier/mod_xsendfile/pull/7
