### ISSUE TITLE
always sending as text/html and ignoring Content-Type

### ISSUE THREAD

**Issue by simonbuehler** [nmaier/mod_xsendfile#26]
hi,

tried to use it under apache 2.4 adn it works - kindof - but sends all data as text/html although i added a `header("Content-Type: image/jpeg");` 

i'm using cakephp and mod_rewrite it that should be relevant, any idea?

**Comment by nmaier** [comment]
I cannot even start to guess what is going wrong without you providing additional details, such as version of mod_xsendfile, server configuration to xsendfile...

**Comment by simonbuehler** [comment]
true, strange thing is that a test.php (outputs a jpg) works in one dir (vhost) but doesn't in another, i have to check that  first, reopening when required
