### ISSUE TITLE
What level of performance should be expected using this module versus a direct download?

### ISSUE THREAD

**Issue by chrisbloom7** [nmaier/mod_xsendfile#3]
I was under the impression that we should see nearly identical speeds in downloading when using this module to force a download via Apache versus linking directly to the file and having Apache send it as usual. However, after wrestling with download speeds on a project I'm working on, I did some benchmarks and found that using XSendFile took longer by a factor of 333%. This test included using a very small PHP script that set the XSendFile header and exited, and then a direct link to the same file in the same directory. The file is approx 150MB. Over 10 downloads to each file the average speed was 3 minutes for the direct link and 10 minutes for the XSendFile method. The server is a 64-bit dual core AMD Opteron @ 2.01 GHz w/ 3.5 GB of RAM running Windows 2003.

Have you performed any similar benchmark tests, and if so have you seen similar stats?

Here's the PHP code I'm using in the test.

```
<?php
include('../../APP/LIB_FILES/DEBUG.php');
$file_path = 'MCRInstaller7p11.exe';
$realpath = dirname(__FILE__) . DIRECTORY_SEPARATOR . $file_path;
if (file_exists($realpath)) {
  $mtime = ($mtime = filemtime($realpath)) ? $mtime : gmtime();
  $size = intval(sprintf("%u", filesize($realpath)));
  header("Content-type: application/force-download");
  header('Content-Type: application/octet-stream');
  if (strstr($_SERVER["HTTP_USER_AGENT"], "MSIE") != false) {
    header("Content-Disposition: attachment; filename=" . urlencode(basename($file_path)) . '; modification-date="' . date('r', $mtime) . '";');
  } else {
    header("Content-Disposition: attachment; filename=\"" . basename($file_path) . '"; modification-date="' . date('r', $mtime) . '";');
  }
  LOGVAR(array(
    'realpath' => $realpath,
    'mtime' => $mtime,
    'size' => $size,
    'HTTP_USER_AGENT' => $_SERVER["HTTP_USER_AGENT"]
  ) , 'Sending TEST file via mod_xsendfile');
  header("X-Sendfile: " . $file_path);
} else {
  LOGVAR('Returning 404', "", X_LOGVAR_ERROR);
  header($_SERVER["SERVER_PROTOCOL"] . ' 404 Not Found');
  header('Status: 404 Not Found');
  header('Content-Length: 0');
  header('Content-Type: text/html');
  echo 'File not found';
}
exit();
?>
```

I stupidly closed the terminal window containing the benchmark results, but I will re-run the tests and post the results.

**Comment by nmaier** [comment]
The code that finally sends out the file (based on the opened file descriptor) is actually a direct copy from httpd/srclib/core.c:default_handler, so the actual performance sending out the file should be basically the same as "direct" access.
There are, however, some costs associated with running your script and some tiny costs checking the header and finding/opening the file.

I just tested my windows binaries to confirm that, and yep, there was just a minimal overhead of less than 5% associated.
Tested on Win7 x64 against official apache 2.2 binaries, 600MB file, localhost to nul (aka. /dev/null) via wget. Got, on average, 202MB/s direct and 199MB/s via a really tiny php script[1](mod_php5).

So either your methodology is flawed or your script actually does more than it is supposed to (but that would be noticeable in a startup delay).

[1]
http://gist.github.com/594491

**Comment by chrisbloom7** [comment]
Hmmm, interesting. I ran the tests again, but the results were the same as I reported. Before running the tests I stripped out the include() and LOGVAR() lines from the PHP script so there is no additional processing going on besides the few native PHP functions.

This is the result of the benchmark test of the direct link:

```
$ ab -n 10 -c 1 -k -v 4 http://xxx.xxx.xxx.164:8001/test/MCRInstaller7p11.exe
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking xxx.xxx.xxx.164 (be patient)...INFO: POST header == 
---
GET /test/MCRInstaller7p11.exe HTTP/1.0
Connection: Keep-Alive
Host: xxx.xxx.xxx.164:8001
User-Agent: ApacheBench/2.3
Accept: */*

---
LOG: header received:
HTTP/1.1 200 OK
Date: Thu, 23 Sep 2010 21:26:02 GMT
Server: Apache/2.2.15 (Win32) mod_ssl/2.2.15 OpenSSL/0.9.8m PHP/5.2.6
Last-Modified: Tue, 07 Sep 2010 18:14:52 GMT
ETag: "6b000000009f21-aa22c70-48faf5f985a72"
Accept-Ranges: bytes
Content-Length: 178400368
Keep-Alive: timeout=5, max=500
Connection: Keep-Alive
Content-Type: application/x-msdownload

MZ?
LOG: Response code = 200

[... 9 more times]

..done

Server Software:        Apache/2.2.15
Server Hostname:        xxx.xxx.xxx.164
Server Port:            8001

Document Path:          /test/MCRInstaller7p11.exe
Document Length:        178400368 bytes

Concurrency Level:      1
Time taken for tests:   1796.477 seconds
Complete requests:      10
Failed requests:        0
Write errors:           0
Keep-Alive requests:    10
Total transferred:      1784007320 bytes
HTML transferred:       1784003680 bytes
Requests per second:    0.01 [#/sec] (mean)
Time per request:       179647.720 [ms] (mean)
Time per request:       179647.720 [ms] (mean, across all concurrent requests)
Transfer rate:          969.78 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    5  15.5      0      49
Processing: 177997 179643 1256.2 179444  181860
Waiting:       52   66  37.5     53     172
Total:      177997 179648 1254.6 179444  181860

Percentage of the requests served within a certain time (ms)
  50%  179444
  66%  180379
  75%  180384
  80%  180988
  90%  181860
  95%  181860
  98%  181860
  99%  181860
 100%  181860 (longest request)
```

And here is the result of the test against the PHP script:

```
$ ab -n 10 -c 1 -k -v 4 http://xxx.xxx.xxx.164:8001/test/index.php
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking xxx.xxx.xxx.164 (be patient)...INFO: POST header == 
---
GET /test/index.php HTTP/1.0
Connection: Keep-Alive
Host: xxx.xxx.xxx.164:8001
User-Agent: ApacheBench/2.3
Accept: */*

---
LOG: header received:
HTTP/1.1 200 OK
Date: Thu, 23 Sep 2010 21:34:10 GMT
Server: Apache/2.2.15 (Win32) mod_ssl/2.2.15 OpenSSL/0.9.8m PHP/5.2.6
X-Powered-By: PHP/5.2.6
Content-Disposition: attachment; filename="MCRInstaller7p11.exe"; modification-date="Tue, 07 Sep 2010 13:14:52 -0500";
Last-Modified: Tue, 07 Sep 2010 18:14:52 GMT
ETag: "6b000000009f21-aa22c70-48faf5f985a72"
Content-Length: 178400368
Keep-Alive: timeout=5, max=500
Connection: Keep-Alive
Content-Type: application/octet-stream

LOG: Response code = 200

[... 9 more times]

..done

Server Software:        Apache/2.2.15
Server Hostname:        xxx.xxx.xxx.164
Server Port:            8001

Document Path:          /test/index.php
Document Length:        178400368 bytes

Concurrency Level:      1
Time taken for tests:   6177.332 seconds
Complete requests:      10
Failed requests:        0
Write errors:           0
Keep-Alive requests:    10
Total transferred:      1784008550 bytes
HTML transferred:       1784003680 bytes
Requests per second:    0.00 [#/sec] (mean)
Time per request:       617733.165 [ms] (mean)
Time per request:       617733.165 [ms] (mean, across all concurrent requests)
Transfer rate:          282.03 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    5  16.3      0      51
Processing: 586560 617728 51105.9 588007  708593
Waiting:       59   61   2.2     60      65
Total:      586560 617733 51116.1 588007  708645

Percentage of the requests served within a certain time (ms)
  50%  588007
  66%  588964
  75%  647202
  80%  707551
  90%  708645
  95%  708645
  98%  708645
  99%  708645
 100%  708645 (longest request)
```

As you can see, the XSendFile test shows an almost 3x increase in d/l time and a 3x decrease in throughput.

I'm going to try stripping the PHP file down further to look like the 2-line code you linked to and re-running the benchmark test. I'll post the results if there's a significant difference.

**Comment by chrisbloom7** [comment]
Still waiting for the 3rd round of ApacheBench tests to finish, but in the meantime I tried fetching w/ wget. Same result for the PHP file: ~10 minutes and only 296kb/sec.

**Comment by chrisbloom7** [comment]
And wget to the direct link shows the same high throughput/short d/l time.

```
$ wget -v http://xxx.xxx.xxx.164:8001/test/index.php
--2010-09-23 20:49:31--  http://xxx.xxx.xxx.164:8001/test/index.php
Connecting to xxx.xxx.xxx.164:8001... connected.
HTTP request sent, awaiting response... 200 OK
Length: 178400368 (170M) [application/x-msdownload]
Saving to: `index.php.1'

100%[==============================================================================>] 178,400,368  297K/s   in 9m 49s  

2010-09-23 20:59:20 (296 KB/s) - `index.php.1' saved [178400368/178400368]

$ wget -v http://xxx.xxx.xxx.164:8001/test/MCRInstaller7p11.exe
--2010-09-23 21:18:12--  http://xxx.xxx.xxx.164:8001/test/MCRInstaller7p11.exe
Connecting to xxx.xxx.xxx.164:8001... connected.
HTTP request sent, awaiting response... 200 OK
Length: 178400368 (170M) [application/x-msdownload]
Saving to: `MCRInstaller7p11.exe'

100%[==============================================================================>] 178,400,368  928K/s   in 3m 9s   

2010-09-23 21:21:21 (920 KB/s) - `MCRInstaller7p11.exe' saved [178400368/178400368]
```

**Comment by nmaier** [comment]
Well, I tested myself, and I guess I found the issue:
You don't EnableSendfile On
See: http://httpd.apache.org/docs/2.2/mod/core.html#enablesendfile

There you have actually found a bug in mod_xsendfile: It interprets EnableSendFile Unset as Off instead of the default On
I'll fix that tomorrow (or better today, here in Germany it is almost 3:42AM by now)

**Comment by nmaier** [comment]
PS: This causes sendfile emulation, which will:
a) Not open the file in sequential mode
b) Read the file in 8k chunks instead of 32k chunks, which leads to
c) Cause a lot of smallish TCP segements

I guess the main problem is that 8k chunks produce 5 full and another half TCP segment on the write, assuming MSS 1492, while 32k produces 21 full and another almost full segment. So with 8k you "loose" half a segment each 6 segments.

**Comment by nmaier** [comment]
The behavior when EnableSendFile is unset is fixed by:
3ba0f30ab0f4b2283106612221ff107d05e00218

**Comment by chrisbloom7** [comment]
Thanks for taking the time to address this. Any idea when an updated Win32 binary will be available?

**Comment by nmaier** [comment]
A binary will be available when I have some times to do a build and release. Actually these binaries are just meant for convenient testing at best, because why would anybody trust me. The source code you can easily read and verify, when it comes to binaries this is a lot harder. Hence I recommend everybody performs their own builds.

Binaries won't be available from me for the next couple of days, because of time constraints. In the meantime just add the following to your Apache config and be done, this actually has the exactly same effect as the fix, i.e. it enables sendfile support in apache:

```
 EnableSendfile on
```

PS: Sorry, I first had a typo in the directive, I now fixed

**Comment by chrisbloom7** [comment]
Finally had a chance to get this setup and do some more testing. The first benchmark shows a 3-fold increase in throughput. Thanks for your help getting to the bottom of this!

**Comment by nmaier** [comment]
FYI: I just released a new version + binaries
