### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by OMGWTFLOL** [nmaier/mod_xsendfile#6]
When I put XSendFile On in the main .htaccess for Wordpress or Drupal, it breaks them both.  Yet if I have it in a subdirectory with just a small simple download script, it seems to work fine.  Any ideas what could be causing that?

**Comment by nmaier** [comment]
There can be many reasons. Without knowing the actual error message I cannot say. Look in the error log
Remember: You need to have AllowOverride FileInfo
